### ISSUE TITLE
Fire armament targeting-area marking radius support

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#56] opened 2018-05-23 19:06 UTC
Basically an Option to draw one or many range circles around the target area, could be cool if they could be colored but that isnt critical.

**Comment by GraionDilach** [comment] 2018-05-23 21:34
Duplicate of #55.

**Comment by ABrandau** [comment] 2018-05-23 22:13
No, I was talking about the AoE indicator of the superweapon

**Comment by GraionDilach** [comment] 2018-05-24 09:28
Oh, sorry. That can be quite complex tbh, considering multi-staged weapons. I'm also notsure if the game supports doing such circular style, think it only supports marking tiles. Gotta check it.

**Closed** 2018-06-24 14:13 UTC
Labels: Feature Request
